import { useMemo } from "react";
import { Link, useSearchParams } from "react-router";
import { ResponsiveContainer, ComposedChart, Bar, Line, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ReferenceLine } from "recharts";
import { useWorkspaceAsset, type ForeignHistory, type MarketWorkspace } from "../data/marketWorkspace";
import { formatDateLabel, formatIdrCompact } from "../data/format";
import { WorkspaceTable } from "../components/WorkspaceTable";

export default function ForeignFlow() {
  const history=useWorkspaceAsset<ForeignHistory>("foreign");const market=useWorkspaceAsset<MarketWorkspace>("market");
  const [params,setParams]=useSearchParams();const period=params.get("period")==="1M"?"1M":"3M";const query=(params.get("search")??"").toLowerCase();
  const data=history.data;
  const start=useMemo(()=>{if(!data)return "";const d=new Date(`${data.as_of}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()-(period==="1M"?1:period==="3M"?3:6));return d.toISOString().slice(0,10);},[data,period]);
  const selected=data?.daily.filter(r=>r.as_of>=start)??[];const available=!!data&&data.start<=start;
  let cumulative=0;const chart=selected.map(r=>{cumulative+=r.net_foreign_value_idr;return {...r,net:r.net_foreign_value_idr/1e12,cumulative:cumulative/1e12};});
  const stocks=(market.data?.records??[]).filter(r=>r.analysis_requested&&r.foreign_net_shares!==null&&(!query||`${r.ticker} ${r.company_name}`.toLowerCase().includes(query))).sort((a,b)=>b.foreign_net_shares!-a.foreign_net_shares!);
  const setParam=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true});};
  return <main className="workspace-page"><header><h1>Foreign flow</h1><p className="meta">Official rupiah net flow · all stock trading markets · {data?formatDateLabel(data.as_of):"Loading dated release"}</p></header>
    <section className="dash-card"><h2>Market foreign flow</h2><div className="workspace-controls" role="group" aria-label="Foreign-flow period">{["1M","3M","6M","YTD","1Y","3Y","5Y"].map(p=><button key={p} className="btn btn-outline" aria-pressed={period===p} disabled={!["1M","3M"].includes(p)} title={["1M","3M"].includes(p)?undefined:"A complete official history for this period is unavailable"} onClick={()=>setParam("period",p)}>{p}</button>)}</div>
    {!data?<p aria-live="polite">{history.loading?"Loading verified daily flow…":history.error}</p>:<><p className="market-level">{available?formatIdrCompact(cumulative):"Period total unavailable"}</p><p className="meta">Net over {period} · {formatDateLabel(selected[0]?.as_of)} → {formatDateLabel(data.as_of)} · {selected.length} verified sessions. Positive = net foreign buy; negative = net foreign sell.</p><div className="workspace-chart" style={{height:350}} role="img" aria-label={`Daily net foreign flow and cumulative net, ${period}, ${formatIdrCompact(cumulative)}`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart} margin={{top:10,right:15,left:0,bottom:8}}><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="as_of" tickFormatter={v=>formatDateLabel(v).slice(0,6)} minTickGap={45} tick={{fontSize:10}}/><YAxis yAxisId="net" orientation="right" tickFormatter={v=>`${v}T`} width={45} tick={{fontSize:10}}/><YAxis yAxisId="cumulative" tickFormatter={v=>`${v}T`} width={48} tick={{fontSize:10}}/><Tooltip labelFormatter={v=>formatDateLabel(String(v))} formatter={(v,name)=>[formatIdrCompact(Number(v)*1e12),name==="net"?"Daily net":"Cumulative net"]}/><ReferenceLine yAxisId="net" y={0} stroke="var(--muted)"/><Bar yAxisId="net" dataKey="net" isAnimationActive={false}>{chart.map(r=><Cell key={r.as_of} fill={r.net>=0?"var(--up)":"var(--down)"}/>)}</Bar><Line yAxisId="cumulative" dataKey="cumulative" stroke="var(--ink)" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><p className="meta">Bars: daily net (right axis). Line: cumulative net within the selected period (left axis). PDF precision is 0.01 billion IDR; sums retain rounding. Longer periods remain unavailable until every session is validated.</p><details><summary>Daily values and official sources</summary><WorkspaceTable rows={selected} rowKey={r=>r.as_of} columns={[{label:"Session",cell:r=>formatDateLabel(r.as_of)},{label:"Daily net · IDR",cell:r=>formatIdrCompact(r.net_foreign_value_idr)},{label:"Official source",cell:r=><a href={r.source.url} target="_blank" rel="noreferrer">IDX Daily Statistics</a>}]}/></details></>}
    </section>
    <section><h2>Stock foreign activity · shares</h2><p className="meta">{market.data?formatDateLabel(market.data.as_of):""} · latest official Stock Summary. These are share quantities, separate from the rupiah market-flow chart. No share quantity is converted to rupiah at a closing price.</p><input className="workspace-search" aria-label="Search foreign-activity ticker" placeholder="Search ticker…" value={params.get("search")??""} onChange={e=>setParam("search",e.target.value)}/><WorkspaceTable rows={stocks} rowKey={r=>r.ticker} columns={[{label:"Stock",cell:r=><Link to={`/ticker/${r.ticker}`}>{r.ticker.replace(".JK","")}</Link>},{label:"Company",cell:r=>r.company_name},{label:"Foreign buy · shares",cell:r=>r.foreign_buy_shares?.toLocaleString()??"Unavailable"},{label:"Foreign sell · shares",cell:r=>r.foreign_sell_shares?.toLocaleString()??"Unavailable"},{label:"Net · shares",cell:r=><span className={(r.foreign_net_shares??0)<0?"negative":"positive"}>{r.foreign_net_shares?.toLocaleString()??"Unavailable"}</span>}]}/></section>
  </main>;
}
