import { Link } from "react-router";
import { useRecordedSectorsSample } from "../data/marketWorkspace";
import { formatDateLabel } from "../data/format";

export default function Methodology() {
  const { data } = useRecordedSectorsSample();
  const stocks = data?.selection.stock_count ?? 66;
  const perSector = data?.selection.stocks_per_sector ?? 6;
  const ytdStocks = data?.coverage?.ytd.stock_count ?? 66;
  const companyFlowStocks = data?.coverage?.company_flow.stock_count ?? 66;
  const expandedCoverage = data?.schema_version === "sectors-expanded-universe-v1" ? data.coverage?.price_history : null;
  return <main className="workspace-page research-workspace">
    <header className="submission-page-heading"><div><div className="eyebrow-muted">The Diffusion · research methods</div><h1>How to read the research</h1><p>Returns, rotation, participation, concentration, and ownership answer different questions. Each reading keeps its own dates, constituents, and evidence.</p></div><Link to="/sources">Coverage &amp; sources</Link></header>
    <section className="dash-card"><h2>Sources and research coverage</h2><p>The Dashboard covers {stocks} stocks across 11 IDX sectors, {perSector} per sector by market-cap ranking on 2 October 2026. Sectors API supplies raw stock closes, native IHSG closes, corporate-action information, and company-level flow. Data through {formatDateLabel(data?.as_of ?? "2026-10-02")}.{expandedCoverage ? ` The 66 added stocks have price history from ${formatDateLabel(expandedCoverage.first_required_price_date)} through ${formatDateLabel(expandedCoverage.end_date)} to support the full replay.` : ""} Year-to-date readings and company-level flow cover {ytdStocks} and {companyFlowStocks} stocks, respectively, through 2 October 2026.</p><p>Market Movers uses the official IDX Stock Summary. Market-level foreign-flow totals come from IDX Daily Statistics; ownership views use dated IDX and KSEI disclosures. Broader adjusted-price comparisons use Yahoo Finance prices retrieved with the yfinance Python client. The source and price basis are shown with each view.</p><p>IDX classifications, curated themes, and disclosed business relationships support the wider market and group views. These baskets are research measures, not official sector indices. Constituents are applied retrospectively; historical results do not represent a portfolio selected at the time.</p></section>
    <section className="dash-card"><h2>Returns and eligibility</h2><p>A stock return is 100 × (ending close / starting close − 1). Excess return subtracts the IHSG return over the same observed dates. A 20D or 60D window uses observed benchmark sessions, rather than calendar days. The group reading is the equal-weighted mean of its eligible stock returns.</p><p>Eligibility is calculated separately for 5D, 20D, 60D, and YTD. A missing YTD baseline does not remove an otherwise valid 20D or 60D reading. The broader context fixes each horizon’s contributor set across the replay window. Sectors participation compares identical names at both dates and displays changes in the paired denominator.</p><p>Sectors closes are unadjusted. Windows affected by splits, rights issues, dividends, and other disclosed mechanical changes are excluded from signal calculations. Missing observations remain missing. The 23 supported Sectors YTD stock readings retain their own ending date of 2 October 2026 during earlier replay selections; no sector meets the five-contributor YTD floor.</p></section>
    <section className="dash-card"><h2>Rotation phase and leadership</h2><p>The default map plots 60D excess return on the horizontal axis and 20D excess minus 60D excess on the vertical axis. Both coordinates use the shared 20D/60D cohort. Optional YTD coordinates also require a shared observed prior-year baseline. Positive horizontal and vertical values mean Leading; negative horizontal and positive vertical mean Improving; both negative mean Lagging; positive horizontal and negative vertical mean Weakening. Empty quadrants are a valid result.</p><p>Leadership is a separate classification. It combines the sign of 20D excess return with acceleration, defined as 5D excess minus 60D excess. Acceleration of at least 1 percentage point counts as improving momentum. A confirmed leadership reading requires at least five eligible names in the shared 5D/20D/60D cohort. Smaller groups retain descriptive returns and hollow map marks.</p></section>
    <section className="dash-card"><h2>Participation and concentration</h2><p>Breadth is the number of stocks with positive 20D excess return divided by the eligible comparison cohort. Diffusion compares integer outperformer counts on identical names. A change of at least 10 percentage points is Broadening or Narrowing. It is firm only when at least max(2, ceiling(10% × cohort size)) names change; otherwise it is fragile. A confirmed diffusion reading requires five contributors and a prior comparison.</p><p>Concentration uses the actual 20D return contributor list. Each stock’s share is its absolute raw or adjusted price return divided by the sum of absolute returns. Top-three concentration adds the three largest shares. It measures concentration of price moves, rather than index weights, ownership, or causal index contribution. Zero gross movement leaves concentration unavailable.</p></section>
    <section className="dash-card"><h2>Interactive curves</h2><p>Stock curves use actual constituent closes. A basket fixes its eligible constituents for the selected chart window, rebases each close to 100 at the window’s start, and averages them equally. IHSG uses the same starting session. Basket contributors need complete matched-session observations and an action-free window in the Sectors universe. Their count can differ from an endpoint return cohort and is disclosed beside the chart.</p><p>Missing individual observations break curves. Corporate actions remain marked on raw-price stock curves. Date, cadence, playback, constituent selection, and group comparison controls let you inspect supported history; they do not create observations or fill gaps.</p></section>
    <section className="dash-card"><h2>Business relationships and ownership</h2><p>The Konglo catalogue reconciles all 34 Arthara business-group labels and retains existing documented portfolio identifiers. Exact named holders and exact listed-company legal names link IDX holdings. Indirect paths follow disclosed stakes of at least 20%; that traversal threshold does not establish control. Listed anchors and issuer affiliations are labelled research relationships. Reference constituent counts are not substituted for verified membership.</p><p>Issuer webpages retrieved on 8 October 2026 may be undated. Membership assessment dates are distinct from publication dates; the catalogue is a retrospective research lens. Holdings, affiliation, and legal control remain separate. A control claim requires a separate issuer statement and citation.</p><p>The 1% and 5% ownership populations retain separate dates and thresholds. Monthly comparisons use retained prior 1% register rows and identical unambiguous published names. Percentage-point differences require both percentages. A 5% row’s published previous share total does not imply a complete prior register or prior percentage. Entries and exits can be disclosure-threshold crossings; they do not establish trades. Ambiguous identities and custody-account reconciliation flags remain visible.</p></section>
  </main>;
}
