import { useMemo } from "react";
import { Link, useSearchParams } from "react-router";
import { useWorkspaceAsset, type OwnershipWorkspace, type MarketWorkspace, type Holder } from "../data/marketWorkspace";
import { formatDateLabel } from "../data/format";
import { WorkspaceTable } from "../components/WorkspaceTable";

const count = (n: number | null | undefined) => n === null || n === undefined ? "Not disclosed" : n.toLocaleString("en-US", { maximumFractionDigits: 0 });
export default function Ownership() {
  const ownership = useWorkspaceAsset<OwnershipWorkspace>("ownership"); const market = useWorkspaceAsset<MarketWorkspace>("market");
  const [params,setParams] = useSearchParams(); const requestedView = params.get("view") ?? "overview"; const view = ["overview","stocks","investors","groups","changes"].includes(requestedView) ? requestedView : "overview"; const five = params.get("register") === "five";
  const query = (params.get("search") ?? "").trim().toLowerCase(); const selectedGroup = params.get("group") ?? "";
  const setParam = (key:string,value:string) => {const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true});};
  const data=ownership.data; const rows = data?.registers[five?"five":"one"] ?? [];
  const multiIssuerNames = useMemo(()=>{const map=new Map<string,Set<string>>();for(const row of rows){const issuers=map.get(row.holder)??new Set<string>();issuers.add(row.ticker);map.set(row.holder,issuers);}return [...map.values()].filter(issuers=>issuers.size>1).length;},[rows]);
  const filtered = rows.filter(r=>!query||`${r.ticker} ${r.issuer} ${r.holder}`.toLowerCase().includes(query));
  const names = useMemo(()=>{
    const map=new Map<string,Holder[]>();for(const row of filtered){const list=map.get(row.holder)??[];list.push(row);map.set(row.holder,list);}return [...map].map(([name,positions])=>({name,positions,stocks:[...new Set(positions.map(r=>r.ticker))]})).sort((a,b)=>b.stocks.length-a.stocks.length||a.name.localeCompare(b.name));
  },[filtered]);
  const changes = (data?.changes ?? []).filter(r=>!query||`${r.ticker} ${r.holder}`.toLowerCase().includes(query)).sort((a,b)=>Math.abs(b.delta_shares??0)-Math.abs(a.delta_shares??0));
  const edges = (market.data?.ownership_edges ?? []).filter(e=>(!selectedGroup||e.group_id===selectedGroup)&&(!query||`${e.holder} ${e.ticker} ${e.group_name}`.toLowerCase().includes(query)));
  const groupNames = [...new Map((market.data?.ownership_edges??[]).map(e=>[e.group_id,e.group_name])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  const holderColumns = [{label:"Stock",cell:(r:Holder)=><Link to={`/ticker/${r.ticker}.JK`}>{r.ticker}</Link>},{label:"Named holder",cell:(r:Holder)=><button className="btn btn-ghost" style={{textAlign:"left",padding:0}} onClick={()=>{const next=new URLSearchParams(params);next.set("view","investors");next.set("search",r.holder);setParams(next);}}>{r.holder}</button>},{label:"Shares",cell:(r:Holder)=>count(r.shares)},{label:"Ownership",cell:(r:Holder)=>`${r.percentage.toFixed(2)}%`},{label:"Classification",cell:(r:Holder)=>r.classification},{label:"Local / foreign",cell:(r:Holder)=>r.local_foreign==="L"?"Local":["A","F"].includes(r.local_foreign)?"Foreign":r.local_foreign},{label:"Evidence",cell:(r:Holder)=><>{r.identity_ambiguous?"Name identity unresolved":"Published name"}{r.account_count!==undefined&&<><br/>{r.account_count} custody accounts{r.account_totals_reconciled===false?" · account cells do not reconcile; published total retained":""}</>}</>}];
  return <main className="workspace-page"><header><h1>Ownership</h1><p className="meta">Full public IDX / KSEI registers. Named positions, disclosed changes and sourced corporate connections.</p></header>
    <nav className="workspace-controls" aria-label="Ownership views">{["overview","stocks","investors","groups","changes"].map(v=><button key={v} className="btn btn-outline" aria-pressed={view===v} onClick={()=>setParam("view",v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav>
    <div className="workspace-controls"><div role="group" aria-label="Ownership register"><button className="btn btn-outline" aria-pressed={!five} onClick={()=>setParam("register","one")}>1% register</button><button className="btn btn-outline" aria-pressed={five} onClick={()=>setParam("register","five")}>5% register</button></div><input className="workspace-search" aria-label="Search ownership ticker, issuer or holder" placeholder="Search ticker, issuer or holder…" value={params.get("search")??""} onChange={e=>setParam("search",e.target.value)}/></div>
    {!data?<p aria-live="polite">{ownership.loading?"Loading official registers…":ownership.error}</p>:<>
      <p className="meta">Selected register: {five?"5%":"1%"} · {formatDateLabel(five?data.five_as_of:data.as_of)} · {rows.length.toLocaleString()} published investor-position rows. {five?"Custody accounts are consolidated using the published investor total, once per block. No address or account identifier is displayed.":"Scripless and certificated holdings are retained separately. Public names do not identify unique SID holders."}</p>
      {five&&<p className="meta">{rows.filter(r=>r.account_totals_reconciled===false).length} investor blocks have custody-account cells that do not reconcile. The official published investor total is retained and each affected row is flagged.</p>}
      {view==="overview"&&<>
        <div className="workspace-stats">{[["Issuers in selected register",new Set(rows.map(r=>r.ticker)).size],["Disclosed positions",rows.length],["Distinct published names",new Set(rows.map(r=>r.holder)).size],["Names across multiple issuers",multiIssuerNames],["Local positions",rows.filter(r=>r.local_foreign==="L").length],["Foreign positions",rows.filter(r=>["A","F"].includes(r.local_foreign)).length]].map(([label,n])=><div className="workspace-stat" key={label}><span className="meta">{label}</span><strong>{Number(n).toLocaleString()}</strong></div>)}</div>
        <section className="dash-card"><h2>What changed in the monthly 1% disclosures</h2><p>{formatDateLabel(data.previous_as_of)} → {formatDateLabel(data.as_of)}. {data.changes.length.toLocaleString()} changed unique-name positions.</p><div className="workspace-stats">{["Disclosure entry","Disclosure exit","Increase","Decrease","Percentage change"].map(kind=><div className="workspace-stat" key={kind}><span className="meta">{kind}</span><strong>{data.changes.filter(r=>r.kind===kind).length}</strong></div>)}</div><p className="meta">An entry or exit can be a threshold crossing. A disclosed change does not establish a trade, its price, or its cause. Equal-name ambiguities are excluded from matching.</p><button className="btn btn-outline" onClick={()=>setParam("view","changes")}>Explore disclosed changes →</button></section>
        <section><h2>Named positions</h2><WorkspaceTable rows={filtered} columns={holderColumns} rowKey={r=>r.row_id}/></section>
      </>}
      {view==="stocks"&&<section><h2>Stock shareholder positions</h2><WorkspaceTable rows={filtered} rowKey={r=>r.row_id} columns={[...holderColumns,{label:five?"Previous reported shares":"Scripless / scrip",cell:r=>five?count(r.previous_shares):`${count(r.scripless)} / ${count(r.scrip)}`}]}/></section>}
      {view==="investors"&&<section><h2>Published holder names</h2><p className="meta">Connections below match the exact published name. They do not merge names into a beneficial-owner identity.</p><WorkspaceTable rows={names} rowKey={r=>r.name} columns={[{label:"Published name",cell:r=>r.name},{label:"Issuer connections",cell:r=>r.stocks.map(code=><Link key={code} style={{marginRight:8}} to={`/ownership?view=stocks&register=${five?"five":"one"}&search=${encodeURIComponent(code)}`}>{code}</Link>)},{label:"Positions",cell:r=>r.positions.length},{label:"Identity",cell:r=>r.positions.some(p=>p.identity_ambiguous)?"Ambiguous same-name positions":"Exact published-name match only"}]}/></section>}
      {view==="groups"&&<section><h2>Ownership connections</h2><p className="meta">Dated disclosed holdings form the graph. Legal control is labelled only where a separate issuer statement supports it. The curated portfolios do not cover every Indonesian business group.</p><label>Portfolio <select className="workspace-search" value={selectedGroup} onChange={e=>setParam("group",e.target.value)}><option value="">All documented portfolios</option>{groupNames.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><p className="meta">{edges.length} sourced connections. Source dates for control statements remain separate from the current holding date.</p><div className="ownership-graph" aria-label="Documented ownership connections">{edges.map(e=><article className="ownership-edge" key={`${e.group_id}:${e.holder}:${e.ticker}`}><div className="ownership-node"><strong>{e.holder}</strong>{e.control_source?.ultimate_holders&&<p className="meta">Issuer-named ultimate controllers: {e.control_source.ultimate_holders.join("; ")} · {formatDateLabel(e.control_source.as_of)}</p>}</div><div><strong>{e.percentage.toFixed(2)}% →</strong><br/><small>{e.relationship}</small></div><Link className="ownership-node" to={`/ownership?view=stocks&search=${e.ticker}`}>{e.ticker}</Link><div className="meta">{e.group_name}<br/>Holding: {formatDateLabel(e.as_of)} · <a href={e.source} target="_blank" rel="noreferrer">Official register</a>{e.control_source&&<><br/>Control statement: {formatDateLabel(e.control_source.as_of)} · <a href={e.control_source.source} target="_blank" rel="noreferrer">Issuer evidence</a></>}</div></article>)}</div>{!market.data&&<p>{market.loading?"Loading sourced connections…":market.error}</p>}</section>}
      {view==="changes"&&<section><h2>Monthly disclosure changes</h2><p className="meta">1% register only · {formatDateLabel(data.previous_as_of)} → {formatDateLabel(data.as_of)}. Missing prior/current values remain undisclosed, not zero.</p><WorkspaceTable rows={changes} rowKey={r=>`${r.ticker}:${r.holder}`} columns={[{label:"Stock",cell:r=><Link to={`/ticker/${r.ticker}.JK`}>{r.ticker}</Link>},{label:"Named holder",cell:r=>r.holder},{label:"Change type",cell:r=>r.kind},{label:"Prior shares",cell:r=>count(r.previous_shares)},{label:"Current shares",cell:r=>count(r.current_shares)},{label:"Reported difference",cell:r=>r.delta_shares===null?"Not comparable":count(r.delta_shares)},{label:"Prior / current %",cell:r=>`${r.previous_percentage?.toFixed(2)??"Undisclosed"} / ${r.current_percentage?.toFixed(2)??"Undisclosed"}`}]}/></section>}
      <details className="dash-card"><summary>Sources and interpretation</summary>{data.sources.map(s=><p key={s.filename}><a href={s.url} target="_blank" rel="noreferrer">Official IDX / KSEI register · {formatDateLabel(s.as_of)}</a><br/><small>SHA-256 {s.sha256}</small></p>)}{data.limitations.map(s=><p key={s} className="meta">{s}</p>)}<p className="meta">Free-float compliance is a separate dated measure. <a href="https://ff.klinikpenyesalan.com/" target="_blank" rel="noreferrer">The referenced free-float site</a> reports a March 2026 screening; it is not the source of these named positions.</p></details>
    </>}
  </main>;
}
